### ISSUE TITLE
Grant lewismc as project collaborator

### ISSUE THREAD

**Issue by lewismc** [giuseppetotaro/ctakes-clinical-pipeline#2]
Hi @giuseppetotaro can you please grant me as a project collaborator? I am ready to push this module to Maven Central.
Thank you very much in advance.

**Comment by giuseppetotaro** [comment]
Hi @lewismc, I have granted you as a project collaborator. Please let me know if you may need something else.
Thanks,
Giuseppe

**Comment by lewismc** [comment]
Thank you @giuseppetotaro top man Viva Juventus
