### ISSUE TITLE
Overwriting input file

### ISSUE THREAD

**Issue by selinachu** [giuseppetotaro/ctakes-clinical-pipeline#3]
In CTAKESClinicalPipelineFactory.java, this line overwrites the input file with xml output:
Line 237            aed.toXML(new FileWriter(args[0]));

**Comment by giuseppetotaro** [comment]
Thanks @selinachu. This line writes out the XML related to AnalysisEngineDescriptor (that has been built programmatically). I have deleted that line from code, therefore the input file is no longer overwritten.
Please let me know if it is necessary to dump out the AE descriptor. I could add a new command-line option.

**Comment by selinachu** [comment]
Thanks @giuseppetotaro! I think having that extra option might be helpful.

**Comment by lewismc** [comment]
@giuseppetotaro has this been addressed? If so then we can close off.

**Comment by giuseppetotaro** [comment]
Hi @lewismc, this has already been addressed. I should have closed it immediately. Sorry about that.
Thanks,
Giuseppe
