### ISSUE TITLE
Make selection of Pipeline Factory-based

### ISSUE THREAD

**Issue by lewismc** [giuseppetotaro/ctakes-clinical-pipeline#4]
Right now one needs to statically define the explicit pipeline they wish to use e.g.

```
CTAKESClinicalPipelineFactory.getDefaultPipeline();
```

It would be better if I could do

```
CTAKESClinicalPipelineFactory.getPipelineForProperty(properties.get("ctakes.pipeline"));
```

This would mean I can adapt my application easily to select fast pipeline, default, pipeline, etc.

**Comment by giuseppetotaro** [comment]
Hi Lewis,

as you suggested, I have added a new static method, called `getPipelineForProperty`, into `CTAKESClinicalPipelineFactory`. This method allows to define the pipeline via configuration file.
More in detail, the method reads the value of the `ctakes.pipeline` property from `ctakes.properties` file (located on `ctakes-clinical-pipeline/src/main/resources`) and then selects the proper method to obtain the pipeline. Six values have been defined through the `CTAKESClinicalPipelineEnum` enumeration: `DEFAULT`, `FAST`, `PARSING`, `TOKEN_PROCESSING`, `NP_CHUNKER`, `STANDARD_CHUNK_ADJUSTER`.

If this improvement addresses your question, I could also add a configuration object (e.g., `CTAKESClinicalPipelineConfig`) to read the name of the pipeline from a user-defined configuration file.

Thanks again @lewismc.
Giuseppe

**Comment by lewismc** [comment]
@giuseppetotaro nice. Excellent work. I think we could probably do some more testing and release another version of this library to Maven Central? wdyt?
